library(ASCAT)

TUMOURNAME = "NASCR-0016"

GC_CONTENT_FILE = "/lustre/scratch110/sanger/sd11/Documents/GenomeFiles/battenberg_snp6/GC_SNP6.txt"
BIRDSEED_REPORT_FILE = "birdseed.report.txt" # No control over the name of this file, as it is automatically generated by APT within cel2baf.logr


###############################################################################
# 2015-05-05
# A pure R ASCAT v2.3 pipeline implementation.
# sd11@sanger.ac.uk
###############################################################################

gender = read.table(BIRDSEED_REPORT_FILE, sep="\t", skip=66, header=T)
sex = as.vector(gender[,"computed_gender"])
sex[sex == "female"] = "XX"
sex[sex == "male"] = "XY"
sex[sex == "unknown"] = NA

# Load the input data
ascat.bc = ascat.loadData("NASCR-0016_mutantLogR.tab_noGCcorr.txt", "NASCR-0016_mutantBAF.tab_noGCcorr.txt", "NASCR-0016_germlineLogR.tab_noGCcorr.txt", "NASCR-0016_germlineBAF.tab_noGCcorr.txt", chrs=c(1:22, "X"), gender=sex)
# Perform GC correction
ascat.bc = ascat.GCcorrect(ascat.bc, GC_CONTENT_FILE)
# Make a plot of the raw data
ascat.plotRawData(ascat.bc)
# Perform segmentation
ascat.bc = ascat.aspcf(ascat.bc)
# Plot the segmented data
ascat.plotSegmentedData(ascat.bc)
# Estimate copy number
ascat.output = ascat.runAscat(ascat.bc)

# Save the output
write.table(ascat.output$segments, file=paste(TUMOURNAME,".segments.txt",sep=""), sep="\t", quote=F, row.names=F)
write.table(ascat.output$aberrantcellfraction, file=paste(TUMOURNAME,".acf.txt",sep=""), sep="\t", quote=F, row.names=F)
write.table(ascat.output$ploidy, file=paste(TUMOURNAME,".ploidy.txt",sep=""), sep="\t", quote=F, row.names=F)
save.image(paste(TUMOURNAME,".RData",sep=""))

q(save="no")
